name: api
description: A simple Shelf server.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dart_jsonwebtoken: ^3.3.1
  http: ^1.5.0
  postgres: ^3.0.0

dev_dependencies:
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.11
